### ISSUE TITLE
Empty screen on start

### ISSUE THREAD

**Issue by inguna87** [alphacep/vosk-android-service#11]
Hi, I would like to say thank you for your hard work. Unfortunately, the apk you have provided doesn't work as it should. When I start the app nothing happens. It doesn't ask if I want to download new models or anything. It just sits on main screen. Tried on Oneplus 7 Pro A10, Huawei P10 A9, Xiaomi Note 10 A11. When I choose it as voice typing service in android settings it pops up but doesn't seem to work, nothing happens.
![Screenshot_20220718-232052](https://user-images.githubusercontent.com/103364968/179628109-0af2339f-bf6a-4370-bbb3-5a7bac633fda.jpg)
Do you mind checking what could be wrong? Thanks a lot in advance

**Comment by inguna87** [comment]
> You can collect logcat with adb to help us on this.

Hopefully, this is enough information. Thank you
[vosk.txt](https://github.com/alphacep/vosk-android-service/files/9136262/vosk.txt)

**Comment by sogaiu** [comment]
I had a similar experience with the apk from here: https://github.com/alphacep/vosk-android-service/releases/tag/0.3.42

I built from https://github.com/alphacep/vosk-android-service/commit/6a719773c100a87ef8d96782326a98f29d714b8c using Android Studio, then installed one of the resulting `.apk` files via adb.  Launching this version of the apk showed a list of language models.

**Comment by dzach** [comment]
I'm getting the exact same empty screen and behavior as @inguna87 on a Samsung Galaxy A5 running Android 7.0. Using vosk-android-service 0.3.42 apk for voice input, it pops up a prompt and an error saying it cannot load the recognizer. Nothing else happens:

![error](https://user-images.githubusercontent.com/1109829/198883469-19ce70a9-5572-41c7-9f59-1720dd75f60f.jpg)

**Comment by inguna87** [comment]
> I had a similar experience with the apk from here: https://github.com/alphacep/vosk-android-service/releases/tag/0.3.42
> 
> I built from [6a71977](https://github.com/alphacep/vosk-android-service/commit/6a719773c100a87ef8d96782326a98f29d714b8c) using Android Studio, then installed one of the resulting `.apk` files via adb. Launching this version of the apk showed a list of language models.
> 
> FWIW, this was on a tablet running Android 10.

Hi, do you mind sharing the apk you have built yourself? Thanks a lot in advance

**Comment by sogaiu** [comment]
@inguna87 I've put some up temporarily here: https://github.com/sogaiu/vosk-android-service/tree/builds/builds

The builds contain extra logging like this:
```
  Log.d(TAG, "onError: " + i);
```
but otherwise they should be the same as what's in https://github.com/alphacep/vosk-android-service/commit/6a719773c100a87ef8d96782326a98f29d714b8c

**Comment by inguna87** [comment]
> @inguna87 I've put some up temporarily here: https://github.com/sogaiu/vosk-android-service/tree/builds/builds
> 
> The builds contain extra logging like this:
> 
> ```
>   Log.d(TAG, "onError: " + i);
> ```
> 
> but otherwise they should be the same as what's in [6a71977](https://github.com/alphacep/vosk-android-service/commit/6a719773c100a87ef8d96782326a98f29d714b8c)

Thank you! We all appreciate your hard work!

**Comment by sogaiu** [comment]
@inguna87 I hope we can all get something working well for our respective situations.  It's really the hard work of others like @nshmyrev and @Doomsdayrs (and may be other people I'm unaware of) though :)

**Comment by inguna87** [comment]
Seems to be fixed now. Thank you @nshmyrev @Doomsdayrs @sogaiu and everyone who is or was working on this project
