### ISSUE TITLE
Speech recognizer won't start

### ISSUE THREAD

**Issue by gweltou** [alphacep/vosk-android-service#28]
Hi,

When started, the SpeechRecognizerActivity gets stuck immediately.
Logcat says "_SpeechRecognizer ..... org.vosk.service ..... E .. bind to recognition service failed_" , when calling `speechRecognizer.startListening(speechRecognizerIntent)`
This error happens with both AnySoftKeyboard and SwiftKey (I didn't try other keyboards).

Note: I have the same error when using [LocalSTT](https://github.com/ccoreilly/LocalSTT)

Android 9 (api 28)
vosk-android-service 0.3.42

![Screenshot_20230223-151818_Vosk](https://user-images.githubusercontent.com/10166907/220933443-10ad3216-eb81-4c19-82d0-f7b8d18ba6aa.jpg)

**Comment by drew-sinha** [comment]
@gweltou , think I fixed this and put in a PR as #29.

**Comment by nshmyrev** [comment]
Merged, let us know how it feels. Thanks @drew-sinha

**Comment by gweltou** [comment]
Amazing ! I can confirm that it solved the issue.
Thanks @drew-sinha
